kind: pipeline
name: default

steps:
- name: docker-push-latest
  image: plugins/docker
  settings:
    repo: izdock/nfs-ganesha
    cache_from: izdock/nfs-ganesha:latest
    create_repository: true
    use_cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    environment:
    - image_from: debian:buster-slim
    - tag_ver_major: 3
    - tag_ver_minor: 2
    - tag_ver_patch: 0
    build_args_from_env:
    - image_from
    - tag_ver_major
    - tag_ver_minor
    - tag_ver_patch
    tags:
    - "latest"
    - "${tag_ver_major}"
    - "${tag_ver_major}.${tag_ver_minor}"
    - "${tag_ver_major}.${tag_ver_minor}-${DRONE_BUILD_NUMBER}"
  when:
    event: [push, tag]
    branch: master
