kind: pipeline
name: default

volumes:
  - name: docker
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

steps:
- name: setup
  image: alpine
  environment: &setup_env
    APP_VER_MAJOR: 3
    APP_VER_MINOR: 2
    #APP_VER_PATCH: 0
  commands:
    - echo -e -n "$${APP_VER_MAJOR}.$${APP_VER_MINOR}-$${DRONE_BUILD_NUMBER}" > VERSION
    - echo -e -n "$${APP_VER_MAJOR}" > .tags
    - echo -e -n ",$${APP_VER_MAJOR}.$${APP_VER_MINOR}" >> .tags
    - echo -e -n ",$${APP_VER_MAJOR}.$${APP_VER_MINOR}-$${DRONE_BUILD_NUMBER}" >> .tags
    - echo -e -n ",latest" >> .tags

- name: publish
  image: plugins/docker
  environment:
    <<: *setup_env
  settings:
    repo: izdock/nfs-ganesha
    #cache_from: izdock/nfs-ganesha:latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args_from_env:
    - IMAGE_FROM
    - APP_VER_MAJOR
    - APP_VER_MINOR
    #- APP_VER_PATCH
  volumes:
  - name: docker
    path: /var/lib/docker
  when:
    event: [push, tag]
    branch: master
    
