kind: pipeline
name: default

steps:
- name: docker-push-latest
  image: plugins/docker
  settings:
    repo: izdock/nfs-ganesha
    cache_from: izdock/nfs-ganesha:latest
    create_repository: true
    use_cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args_from_env:
    - IMAGE_FROM
    - TAG_VER_MAJOR
    - TAG_VER_MINOR
    - TAG_VER_PATCH
    tags:
    - latest
    - ${TAG_VER_MAJOR}
    - ${TAG_VER_MAJOR}.${TAG_VER_MINOR}
    - ${TAG_VER_MAJOR}.${TAG_VER_MINOR}-${DRONE_BUILD_NUMBER}
  when:
    event: [push, tag]
    branch: master
