kind: pipeline
name: nfs-ganesha

steps:
- name: prepare
  image: busybox
  commands:
    - mkdir -p /cache/${DRONE_REPO}/docker
  volumes:
    - name: cache
      path: /cache

- name: docker-push-latest
  image: plugins/docker
  settings:
    repo: izdock/nfs-ganesha
    #cache_from: izdock/nfs-ganesha:latest
    create_repository: true
    use_cache: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - image_from: debian:buster-slim
    - tag_ver_major: 3
    - tag_ver_minor: 0
    - tag_ver_patch: 2
    tags:
    - latest
    - '3'
    - '3.2'
    - '3.2-${DRONE_BUILD_NUMBER}'
  volumes:
  - name: docker
    path: /var/lib/docker

volumes:
- name: cache
  host:
    path: /var/cache
- name: docker
  host:
    path: /var/cache/${DRONE_REPO}/docker
